create table authors (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table authors_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table books (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), isbn varchar(255), price double precision, published_on varchar(255), title varchar(255), author_id bigint not null, publisher_id bigint not null, primary key (id)) engine=InnoDB;
create table books_audit (id bigint not null, rev integer not null, revtype tinyint, isbn varchar(255), price double precision, published_on varchar(255), title varchar(255), author_id bigint, publisher_id bigint, primary key (id, rev)) engine=InnoDB;
create table customers (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table customers_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), email varchar(255), name varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
create table publishers (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), name varchar(255), phone varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table publishers_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), name varchar(255), phone varchar(255), url varchar(255), primary key (id, rev)) engine=InnoDB;
create table revinfo (rev integer not null auto_increment, revtstmp bigint, primary key (rev)) engine=InnoDB;
create table transaction (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), customer_id bigint not null, primary key (id)) engine=InnoDB;
create table transaction_item (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), quantity integer, book_id bigint, transaction_id bigint not null, primary key (id)) engine=InnoDB;
create table transaction_items_audit (id bigint not null, rev integer not null, revtype tinyint, quantity integer, book_id bigint, transaction_id bigint, primary key (id, rev)) engine=InnoDB;
create table transactions_audit (id bigint not null, rev integer not null, revtype tinyint, customer_id bigint, primary key (id, rev)) engine=InnoDB;
create table warehouse_books (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), quantity integer, book_id bigint, warehouse_id bigint not null, primary key (id)) engine=InnoDB;
create table warehouse_books_audit (id bigint not null, rev integer not null, revtype tinyint, quantity integer, book_id bigint, warehouse_id bigint, primary key (id, rev)) engine=InnoDB;
create table warehouses (id bigint not null auto_increment, created datetime, created_by varchar(255), last_modified datetime, last_modified_by varchar(255), address varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table warehouses_audit (id bigint not null, rev integer not null, revtype tinyint, address varchar(255), phone varchar(255), primary key (id, rev)) engine=InnoDB;
alter table authors_audit add constraint FK4h9eexvqe2tf95cot5h3lmj2f foreign key (rev) references revinfo (rev);
alter table books add constraint FKfjixh2vym2cvfj3ufxj91jem7 foreign key (author_id) references authors (id);
alter table books add constraint FKayy5edfrqnegqj3882nce6qo8 foreign key (publisher_id) references publishers (id);
alter table books_audit add constraint FKfyfj7ys56hvrijh5f6uklakbl foreign key (rev) references revinfo (rev);
alter table customers_audit add constraint FKomk36ryme5vkw0iwyfdqmrs3n foreign key (rev) references revinfo (rev);
alter table publishers_audit add constraint FKbqi9jslry84m8frk3oon2o5lm foreign key (rev) references revinfo (rev);
alter table transaction add constraint FKu2anf16eh7wulf2gnh2g713u foreign key (customer_id) references customers (id);
alter table transaction_item add constraint FK9ybjrwtlkrgl7adwh7lde5np4 foreign key (book_id) references books (id);
alter table transaction_item add constraint FK1wc2dvhj3oos47in473fqi3q8 foreign key (transaction_id) references transaction (id);
alter table transaction_items_audit add constraint FK5pto4l39bs3j838ttv3x5ngrn foreign key (rev) references revinfo (rev);
alter table transactions_audit add constraint FKf90u6a4gsptmq5lwbpbd9c78l foreign key (rev) references revinfo (rev);
alter table warehouse_books add constraint FKi1euw05gm0yxv109rncro00y2 foreign key (book_id) references books (id);
alter table warehouse_books add constraint FKlpyljyncrntrvjc1l7p01l689 foreign key (warehouse_id) references warehouses (id);
alter table warehouse_books_audit add constraint FKi148dp5qvr0ter3fxhc8re1bj foreign key (rev) references revinfo (rev);
alter table warehouses_audit add constraint FKt98ml3inrn1yn4mkl342v0f1l foreign key (rev) references revinfo (rev);